// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0hfjd9i37FGZ_-Um0hGcZXoXBv2oBsUY',
    appId: '1:141420396912:web:b9b73b5e880a8878438fb5',
    messagingSenderId: '141420396912',
    projectId: 'perski-81781',
    authDomain: 'perski-81781.firebaseapp.com',
    storageBucket: 'perski-81781.firebasestorage.app',
    measurementId: 'G-B8DEY59R65',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk-DJk29l2pmxHQivj2huLW68OpMYqTHw',
    appId: '1:141420396912:android:cb146979e38035a0438fb5',
    messagingSenderId: '141420396912',
    projectId: 'perski-81781',
    storageBucket: 'perski-81781.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7fBzoruMuAihO48JR-HAGRB_n0gxubGg',
    appId: '1:141420396912:ios:66576d6521e44127438fb5',
    messagingSenderId: '141420396912',
    projectId: 'perski-81781',
    storageBucket: 'perski-81781.firebasestorage.app',
    iosClientId: '141420396912-4ur17v0ednbjqmg2i8os7p62shbetlb4.apps.googleusercontent.com',
    iosBundleId: 'com.example.baymax',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7fBzoruMuAihO48JR-HAGRB_n0gxubGg',
    appId: '1:141420396912:ios:66576d6521e44127438fb5',
    messagingSenderId: '141420396912',
    projectId: 'perski-81781',
    storageBucket: 'perski-81781.firebasestorage.app',
    iosClientId: '141420396912-4ur17v0ednbjqmg2i8os7p62shbetlb4.apps.googleusercontent.com',
    iosBundleId: 'com.example.baymax',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0hfjd9i37FGZ_-Um0hGcZXoXBv2oBsUY',
    appId: '1:141420396912:web:bdcaa20e66afb38c438fb5',
    messagingSenderId: '141420396912',
    projectId: 'perski-81781',
    authDomain: 'perski-81781.firebaseapp.com',
    storageBucket: 'perski-81781.firebasestorage.app',
    measurementId: 'G-J0HXN15DGW',
  );
}
